import type { AssistantActionDefinition } from "@/features/assistant-actions/types";

export const assistantActionCatalog: AssistantActionDefinition[] = [
  {
    command: "getTodayUrgencies",
    description: "Retourne les deadlines et urgences à absorber aujourd’hui.",
    example: "Montre-moi les urgences du jour",
    exposure: "safe",
    key: "today-urgencies",
    kind: "read",
    label: "Urgences du jour",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "getUnprocessedEmails",
    description: "Liste les emails encore non traités ou à revoir.",
    example: "Quels emails ne sont pas encore qualifiés ?",
    exposure: "safe",
    key: "emails-unprocessed",
    kind: "read",
    label: "Emails non traités",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "getEmailActivity",
    description:
      "Produit un listing factuel des emails reçus sur une période et de la première réponse sortante associée.",
    example: "Liste les mails reçus la semaine dernière avec mes heures de réponse",
    exposure: "safe",
    key: "emails-activity",
    kind: "read",
    label: "Activité email",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "getRequestsWithoutAssignee",
    description: "Retourne les demandes encore sans pilote assigné.",
    example: "Quelles demandes sont sans owner ?",
    exposure: "safe",
    key: "requests-unassigned",
    kind: "read",
    label: "Demandes sans assignation",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "getBlockedProductions",
    description: "Retourne les productions bloquées.",
    example: "Quelles productions sont bloquées ?",
    exposure: "safe",
    key: "productions-blocked",
    kind: "read",
    label: "Productions bloquées",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "getHighRiskProductions",
    description: "Retourne les productions high risk / critical.",
    example: "Montre-moi les productions à haut risque",
    exposure: "safe",
    key: "productions-high-risk",
    kind: "read",
    label: "Productions à risque",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "searchClientHistory",
    description: "Recherche les signaux récents sur un client.",
    example: "Cherche l’historique client Etam",
    exposure: "safe",
    key: "client-history",
    kind: "read",
    label: "Historique client",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "searchModelHistory",
    description: "Recherche les signaux récents sur un modèle.",
    example: "Cherche l’historique du modèle X",
    exposure: "safe",
    key: "model-history",
    kind: "read",
    label: "Historique modèle",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "prepareReplyDraft",
    description: "Prépare un brouillon contextualisé sans jamais l’envoyer.",
    example: "Prépare un accusé de réception pour le mail ETAM",
    exposure: "safe",
    key: "reply-draft",
    kind: "write",
    label: "Préparer une réponse",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "runGmailSync",
    description: "Relance la synchronisation Gmail partagée pour importer les derniers emails.",
    example: "Relance la sync Gmail partagée",
    exposure: "safe",
    key: "gmail-sync-run",
    kind: "write",
    label: "Synchroniser Gmail",
    permission: "emails.sync",
    safeForOpenClaw: true,
  },
  {
    command: "runEmailOpsCycle",
    description: "Synchronise Gmail puis trie et enrichit les emails CRM un par un.",
    example: "Lance le cycle assistant emails du matin",
    exposure: "safe",
    key: "email-ops-cycle",
    kind: "write",
    label: "Traiter l’inbox email",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "setEmailInboxBucket",
    description: "Classe un email dans Important, Pub ou À vérifier.",
    example: "Classe ce mail en important",
    exposure: "safe",
    key: "email-triage-bucket",
    kind: "write",
    label: "Classer un email",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "writeDailySummary",
    description:
      "Écrit la synthèse quotidienne Claw, découpée par client, avec points clés, risques et actions à suivre.",
    example: "Écris la synthèse de la journée client par client",
    exposure: "safe",
    key: "daily-summary-write",
    kind: "write",
    label: "Écrire une synthèse",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "createClient",
    description: "Crée un client CRM ou réutilise l’existant si le nom ou le code matchent.",
    example: "Crée le client Maison 123",
    exposure: "safe",
    key: "client-create",
    kind: "write",
    label: "Créer un client",
    permission: "clients.create",
    safeForOpenClaw: true,
  },
  {
    command: "assignClientToEmail",
    description: "Assigne un client existant à un email pour enrichir sa qualification CRM.",
    example: "Assigne le client Etam au mail X",
    exposure: "safe",
    key: "email-client-assign",
    kind: "write",
    label: "Assigner un client à un email",
    permission: "emails.qualify",
    safeForOpenClaw: true,
  },
  {
    command: "attachEmailToRequest",
    description: "Rattache un email existant à une demande CRM déjà créée.",
    example: "Rattache ce mail à la demande Etam target price",
    exposure: "safe",
    key: "email-request-attach",
    kind: "write",
    label: "Rattacher un email",
    permission: "emails.qualify",
    safeForOpenClaw: true,
  },
  {
    command: "createRequest",
    description: "Crée une demande CRM structurée avec type, priorité et contexte métier.",
    example: "Crée une demande price_request pour Etam",
    exposure: "safe",
    key: "request-create",
    kind: "write",
    label: "Créer une demande",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "createTask",
    description: "Crée une tâche CRM reliée à une demande si nécessaire.",
    example: "Crée une task deadline_check sur la demande X",
    exposure: "safe",
    key: "task-create",
    kind: "write",
    label: "Créer une tâche",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "updateRequest",
    description: "Met à jour une demande CRM existante: statut, priorité ou assignation.",
    example: "Passe la demande X en attente validation et assigne-la à Sarah",
    exposure: "safe",
    key: "request-update",
    kind: "write",
    label: "Modifier une demande",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "updateTask",
    description: "Met à jour une tâche CRM existante: statut, priorité, responsable ou échéance.",
    example: "Marque la tâche X en cours et mets-la en priorité haute",
    exposure: "safe",
    key: "task-update",
    kind: "write",
    label: "Modifier une tâche",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "createDeadline",
    description: "Crée une deadline liée à un dossier.",
    example: "Ajoute une deadline au 05/04 sur la demande X",
    exposure: "safe",
    key: "deadline-create",
    kind: "write",
    label: "Créer une deadline",
    permission: "assistant.manage",
    safeForOpenClaw: true,
  },
  {
    command: "addNoteToRequest",
    description: "Ajoute une note métier directement sur une demande.",
    example: "Ajoute une note sur la demande X",
    exposure: "safe",
    key: "request-note",
    kind: "write",
    label: "Noter une demande",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "addNoteToProduction",
    description: "Ajoute une note opérationnelle sur une production.",
    example: "Ajoute un blocage sur la prod Y",
    exposure: "safe",
    key: "production-note",
    kind: "write",
    label: "Noter une production",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
];
