import type { AssistantActionDefinition } from "@/features/assistant-actions/types";

export const assistantActionCatalog: AssistantActionDefinition[] = [
  {
    command: "getTodayUrgencies",
    description: "Retourne les deadlines et urgences à absorber aujourd’hui.",
    example: "Montre-moi les urgences du jour",
    exposure: "safe",
    key: "today-urgencies",
    kind: "read",
    label: "Urgences du jour",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "getUnprocessedEmails",
    description: "Liste les emails encore non traités ou à revoir.",
    example: "Quels emails ne sont pas encore qualifiés ?",
    exposure: "safe",
    key: "emails-unprocessed",
    kind: "read",
    label: "Emails non traités",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "getRequestsWithoutAssignee",
    description: "Retourne les demandes encore sans pilote assigné.",
    example: "Quelles demandes sont sans owner ?",
    exposure: "safe",
    key: "requests-unassigned",
    kind: "read",
    label: "Demandes sans assignation",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "getBlockedProductions",
    description: "Retourne les productions bloquées.",
    example: "Quelles productions sont bloquées ?",
    exposure: "safe",
    key: "productions-blocked",
    kind: "read",
    label: "Productions bloquées",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "getHighRiskProductions",
    description: "Retourne les productions high risk / critical.",
    example: "Montre-moi les productions à haut risque",
    exposure: "safe",
    key: "productions-high-risk",
    kind: "read",
    label: "Productions à risque",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "searchClientHistory",
    description: "Recherche les signaux récents sur un client.",
    example: "Cherche l’historique client Etam",
    exposure: "safe",
    key: "client-history",
    kind: "read",
    label: "Historique client",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "searchModelHistory",
    description: "Recherche les signaux récents sur un modèle.",
    example: "Cherche l’historique du modèle X",
    exposure: "safe",
    key: "model-history",
    kind: "read",
    label: "Historique modèle",
    permission: "assistant.read",
    safeForOpenClaw: true,
  },
  {
    command: "prepareReplyDraft",
    description: "Prépare un brouillon contextualisé sans jamais l’envoyer.",
    example: "Prépare un accusé de réception pour le mail ETAM",
    exposure: "safe",
    key: "reply-draft",
    kind: "write",
    label: "Préparer une réponse",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "createTask",
    description: "Crée une tâche CRM reliée à une demande si nécessaire.",
    example: "Crée une task deadline_check sur la demande X",
    exposure: "safe",
    key: "task-create",
    kind: "write",
    label: "Créer une tâche",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "createDeadline",
    description: "Crée une deadline liée à un dossier.",
    example: "Ajoute une deadline au 05/04 sur la demande X",
    exposure: "restricted",
    key: "deadline-create",
    kind: "write",
    label: "Créer une deadline",
    permission: "assistant.manage",
    safeForOpenClaw: false,
  },
  {
    command: "addNoteToRequest",
    description: "Ajoute une note métier directement sur une demande.",
    example: "Ajoute une note sur la demande X",
    exposure: "safe",
    key: "request-note",
    kind: "write",
    label: "Noter une demande",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
  {
    command: "addNoteToProduction",
    description: "Ajoute une note opérationnelle sur une production.",
    example: "Ajoute un blocage sur la prod Y",
    exposure: "safe",
    key: "production-note",
    kind: "write",
    label: "Noter une production",
    permission: "assistant.write.safe",
    safeForOpenClaw: true,
  },
];
