export {
  appRoleLabels,
  canCloseRequest,
  canCreateDeadlines,
  canCreateDocuments,
  canManageRequests,
  canModifyProduction,
  canReadMonitoring,
  canRole,
  canSyncGmail,
  canUseAssistantReadActions,
  canUseAssistantSafeActions,
  canUseAssistantSensitiveActions,
  DEFAULT_APP_ROLE,
  getPermissionsForRole,
  isExplicitAdminRole,
  normalizeAppUserRole,
  type AppPermission,
} from "@/features/auth/permissions";
